language: node_js
node_js:
- '5'
addons:
  code_climate:
    repo_token: "21b85990021aeaed92fd89b5657d5e9db4a7d72d3ce9be66ebdef922f5fd56a1"
before_script:
- npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: I0nPREHN897n+6iYiSLO5tHSlqUguRHsLGQ7OVifNPVGY/NWdEDsz0iW8Z/QZG3ex7ov9HzKRgATKBEILoYXBkZdZwwUN2Td5e5HPio4zLey97ztBSAgAVMcZx7tRMP17MXLPYw9NePSczNYSZNsTm9Iqmv91cFrn/JvPujxV/qq3wH1lk9jf3nIWWCxgfL3HgG9OcsJ7+tQBCgsX8RwHbFGHt2DPkmDi76s3AmXV7Ek6XdHw1Fh9/LpOW2oWpc1cBCZG8eoy2ThPYr795QcMKBq1plCVhgzGO17scz/Yg3wGyM6Z3VJ6Mk3HDh0RKVfertNFaYnC5S26jrHhLDw2ltclcNum1Qo+w2pDK88RGBEOFsFUdUSNL2wKyf2l9yD4pZwXWqcb6gcwYlMzNuCtYZ21I9C0R1Xdk0IQHc3NFfuOGvls6RUBPRwD3Nj8U3QCWBhVPfw1l+ZQ6813xktZMkf40xyleJ6ZFlXzIcxcYcdyJHuoRsMjlZRLl+2ena4RVFyoZixqJEacPaSOHhyc+RHqf49YkSmQR2UribG7e1zMp6wzHlNZcpTEH1qW765ctsYGiJHyDR7WGp7lHVHlox5qxXvg3MfYitIoWnRhrxCQJEGVx5JbBvInKzy+pzgM+S1Z6agWvQbo5QL+yLySTCRBUjvRjXSGR2mJo3pr3k=
  on:
    tags: true
    branches: true
after_success:
- bash <(curl -s https://codecov.io/bash)
branches:
  only:
  - "/^v[0-9]/"
